### ISSUE TITLE
Receive data error

### ISSUE THREAD

**Issue by aliasghar1721** [MechMindRobotics/mecheye_cpp_samples#22]
While running the basic ConnectAndCaptureImage.cpp example, I get the following output:

> Find Mech-Eye Industrial 3D Cameras...
Receive Data error.
10060
No Mech-Eye Industrial 3D Cameras found.

However, I am able to connect to the camera and capture images using the Mech-Eye Viewer app.

I am using the Mech-Eye Pro S model.

Any recommendations for fixing this issue?

**Comment by shuaidang** [comment]
Hello, this issue pertains to a camera communication problem. It seems that your program is running normally but not detecting the camera. Please refer to the community's methods for troubleshooting: [link to community post](https://community.mech-mind.com/t/faq-using-mech-eye-api/862). If you know the IP address of the camera, you can try using the `connect` function: [how-to-connect-to-a-camera-via-its-ip-address-using-mech-eye-api](https://community.mech-mind.com/t/how-to-connect-to-a-camera-via-its-ip-address-using-mech-eye-api/1121).
